### ISSUE TITLE
IPv4 octet count is incorrect

### ISSUE THREAD

**Issue by avian2** [MorbZ/munin-ipv6#2]
Even with only IPv6 traffic this plugin displays at most 50% IPv6 use. 

`/proc/net/dev` counts _total_ number of octets sent through network interfaces (so both IPv4 and IPv6). On the other hand, this code expects that it counts only IPv4:

```
ipv4=$( echo "`egrep -v bond\|lo /proc/net/dev | awk -F' ' '{print $2+$10}' | paste -sd+ | bc` * 8" | bc )
```

https://stackoverflow.com/questions/3521678/linux-what-are-means-of-fields-in-proc-net-dev

**Comment by Epaphus** [comment]
I saw the same issue, I thought it was odd that no matter how much IPv6 traffic I had, it was always 50%,

I have done a pull request to fix this. 
#3
